package io.nereusstream.delay.store;

import io.nereusstream.delay.protocol.Bytes;
import io.nereusstream.delay.protocol.CheckpointUploadIntentV1;
import io.nereusstream.delay.protocol.CheckpointUploadStateV1;
import io.nereusstream.delay.protocol.SourcePosition;

import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.util.Objects;
import java.util.function.LongSupplier;

/**
 * Bounded local execution of one scheduled checkpoint attempt.
 *
 * <p>The scheduler claim is checked before any filesystem or provider I/O and
 * is completed with the same exact handle after the attempt, including a
 * failed attempt. The checkpoint identity comes from the already-created
 * {@link CheckpointUploadIntentV1}; it is never generated by this class. If a
 * prior attempt created the same local directory but lost its upload/catalog
 * response, the directory is reused after the physical manifest checks pass.
 * This keeps retry identity stable without making a local directory an
 * authority.</p>
 *
 * <p>This class composes the local scheduler, RocksDB checkpoint and upload /
 * catalog ordering only. Source assignment, Owner Lease/session authority,
 * Object Store attestation/quiescence and the production Oxia transaction
 * remain outside this boundary.</p>
 */
public final class CheckpointExecutionCoordinator {
    private final CheckpointScheduler scheduler;
    private final ShardStore store;
    private final CheckpointPublicationCoordinator publicationCoordinator;

    public CheckpointExecutionCoordinator(final CheckpointScheduler scheduler,
                                          final ShardStore store,
                                          final CheckpointPublicationCoordinator publicationCoordinator) {
        this.scheduler = Objects.requireNonNull(scheduler, "scheduler");
        this.store = Objects.requireNonNull(store, "store");
        this.publicationCoordinator = Objects.requireNonNull(publicationCoordinator, "publicationCoordinator");
    }

    /**
     * Validates the process-local claim and immutable execution identity
     * without starting filesystem or provider I/O.  Work-class admission uses
     * this preflight before it places the exact checkpoint action in the
     * bounded {@code CHECKPOINT} queue; {@link #execute} repeats the same
     * checks after any queue wait.
     */
    public void requireCurrentExecution(final CheckpointScheduler.ScheduledCheckpoint claim,
                                        final CheckpointUploadIntentV1 pending) {
        scheduler.requireCurrentClaim(Objects.requireNonNull(claim, "claim"));
        validatePendingIdentity(Objects.requireNonNull(pending, "pending"), claim);
    }

    /**
     * Executes one exact scheduler claim. A failed publication still clears
     * the claim and schedules a later retry; if that completion cannot be
     * proven, the scheduler deliberately retains the in-flight claim and the
     * failure is propagated.
     */
    public ExecutionResult execute(final CheckpointScheduler.ScheduledCheckpoint claim,
                                   final Path checkpointDirectory,
                                   final CheckpointUploadIntentV1 pending,
                                   final CheckpointManifestFactory manifestFactory,
                                   final long uploadNowEpochMs,
                                   final LongSupplier completionClock,
                                   final CheckpointUploadAdapter adapter) {
        Objects.requireNonNull(claim, "claim");
        Objects.requireNonNull(checkpointDirectory, "checkpointDirectory");
        Objects.requireNonNull(pending, "pending");
        Objects.requireNonNull(manifestFactory, "manifestFactory");
        Objects.requireNonNull(completionClock, "completionClock");
        Objects.requireNonNull(adapter, "adapter");
        scheduler.requireCurrentClaim(claim);

        Path createdDirectory = null;
        boolean reusedExistingDirectory = false;
        CheckpointManifest manifest = null;
        CheckpointPublicationCoordinator.CheckpointPublication publication = null;
        long nextDueEpochMs = -1;
        Throwable primaryFailure = null;
        try {
            if (uploadNowEpochMs < 0) {
                throw new IllegalArgumentException("uploadNowEpochMs must be non-negative");
            }
            validatePendingIdentity(pending, claim);
            final ExistingDirectory existing = existingCheckpointDirectory(checkpointDirectory, pending);
            if (existing.exists()) {
                reusedExistingDirectory = true;
                createdDirectory = checkpointDirectory;
            } else {
                createdDirectory = store.createCheckpoint(checkpointDirectory, pending.checkpointId());
            }

            manifest = Objects.requireNonNull(manifestFactory.create(createdDirectory, store),
                    "checkpoint manifest factory returned null");
            validateManifestAgainstStore(manifest, pending);
            publication = publicationCoordinator.publish(createdDirectory, pending, manifest,
                    pending.baseCatalogGeneration(), uploadNowEpochMs, adapter);
        } catch (RuntimeException | Error failure) {
            primaryFailure = failure;
            throw failure;
        } finally {
            try {
                final long completedAtEpochMs = readCompletionTime(completionClock);
                nextDueEpochMs = scheduler.complete(claim, completedAtEpochMs);
            } catch (RuntimeException | Error completionFailure) {
                if (primaryFailure != null && completionFailure != primaryFailure) {
                    primaryFailure.addSuppressed(completionFailure);
                } else if (primaryFailure == null) {
                    throw completionFailure;
                }
            }
        }
        return new ExecutionResult(createdDirectory, reusedExistingDirectory, manifest, publication,
                nextDueEpochMs);
    }

    private ExistingDirectory existingCheckpointDirectory(final Path checkpointDirectory,
                                                            final CheckpointUploadIntentV1 pending) {
        if (Files.isSymbolicLink(checkpointDirectory)) {
            throw new IllegalStateException("checkpoint directory must not be a symbolic link");
        }
        if (!Files.exists(checkpointDirectory, LinkOption.NOFOLLOW_LINKS)) {
            return new ExistingDirectory(false);
        }
        if (!Files.isDirectory(checkpointDirectory, LinkOption.NOFOLLOW_LINKS)) {
            throw new IllegalStateException("checkpoint target exists but is not a directory");
        }
        final byte[] localCheckpointId = store.runtimeMetadata().lastCheckpointId();
        if (localCheckpointId == null
                || !Bytes.constantTimeEquals(localCheckpointId, pending.checkpointId())) {
            throw new IllegalStateException("existing checkpoint directory has a different local checkpoint identity");
        }
        return new ExistingDirectory(true);
    }

    private void validatePendingIdentity(final CheckpointUploadIntentV1 pending,
                                         final CheckpointScheduler.ScheduledCheckpoint claim) {
        if (pending.state() != CheckpointUploadStateV1.PENDING_UPLOAD) {
            throw new IllegalArgumentException("checkpoint execution requires PENDING_UPLOAD intent");
        }
        if (!claim.shardId().equals(store.shardId())
                || !pending.shard().shardId().equals(store.shardId())) {
            throw new IllegalArgumentException("checkpoint claim, upload intent and Store belong to different shards");
        }
        if (!Bytes.constantTimeEquals(pending.sourceStoreIncarnation(),
                uuidBytes(store.metadata().storeIncarnationUuid()))) {
            throw new IllegalArgumentException("checkpoint upload intent Store Incarnation does not match active Store");
        }
    }

    private void validateManifestAgainstStore(final CheckpointManifest manifest,
                                              final CheckpointUploadIntentV1 pending) {
        if (!manifest.shardId().equals(store.shardId())
                || !Bytes.constantTimeEquals(manifest.checkpointId(), pending.checkpointId())
                || !Bytes.constantTimeEquals(manifest.recoveryLineageId(), pending.recoveryLineageId())) {
            throw new IllegalArgumentException("checkpoint manifest identity does not match execution intent");
        }
        final StoreMetadata metadata = store.metadata();
        if (manifest.storeFormatVersion() != metadata.storeFormatVersion()
                || !Bytes.constantTimeEquals(manifest.dbIdentity(), metadata.dbIdentity())
                || !manifest.sourceStoreIncarnation().equals(metadata.storeIncarnationUuid())) {
            throw new IllegalArgumentException("checkpoint manifest does not describe the active Store identity");
        }
        final byte[] localCheckpointId = store.runtimeMetadata().lastCheckpointId();
        if (localCheckpointId == null || !Bytes.constantTimeEquals(localCheckpointId, pending.checkpointId())) {
            throw new IllegalStateException("active Store does not carry the checkpoint identity being published");
        }
        final SourcePosition applied = store.appliedShardLogPosition();
        if (applied == null || !Bytes.constantTimeEquals(applied.canonicalBytes(),
                manifest.appliedShardLogPosition().canonicalBytes())) {
            throw new IllegalArgumentException("checkpoint manifest source position does not match the Store");
        }
        if (store.shardMutationSequence() != manifest.shardMutationSequence()) {
            throw new IllegalArgumentException("checkpoint manifest mutation sequence does not match the Store");
        }
        if (!store.runtimeMetadata().evidenceCursors().equals(manifest.evidenceCursors())) {
            throw new IllegalArgumentException("checkpoint manifest evidence cursors do not match the Store");
        }
        if (store.controlSnapshot() == null
                || !Bytes.constantTimeEquals(store.controlSnapshot().snapshotDigest(),
                manifest.controlStateDigest())) {
            throw new IllegalArgumentException("checkpoint manifest control snapshot does not match the Store");
        }
    }

    private static long readCompletionTime(final LongSupplier clock) {
        final long value = clock.getAsLong();
        if (value < 0) {
            throw new IllegalArgumentException("checkpoint completion clock returned a negative time");
        }
        return value;
    }

    private static byte[] uuidBytes(final java.util.UUID value) {
        return java.nio.ByteBuffer.allocate(16).putLong(value.getMostSignificantBits())
                .putLong(value.getLeastSignificantBits()).array();
    }

    private record ExistingDirectory(boolean exists) {
    }

    public record ExecutionResult(Path checkpointDirectory,
                                  boolean reusedExistingDirectory,
                                  CheckpointManifest manifest,
                                  CheckpointPublicationCoordinator.CheckpointPublication publication,
                                  long nextDueEpochMs) {
        public ExecutionResult {
            Objects.requireNonNull(checkpointDirectory, "checkpointDirectory");
            Objects.requireNonNull(manifest, "manifest");
            Objects.requireNonNull(publication, "publication");
            if (nextDueEpochMs < 0) {
                throw new IllegalArgumentException("nextDueEpochMs must be non-negative");
            }
        }
    }

    @FunctionalInterface
    public interface CheckpointManifestFactory {
        CheckpointManifest create(Path checkpointDirectory, ShardStore store);
    }
}
